services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpassword1234
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: testpassword1234
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\\DevProjects\\DockerData\\redis-data
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\\DevProjects\\DockerData\\mysql-data